title: Shichen Li's Page
logo: assets/me.JPG
theme: jekyll-theme-minimal
blog_description: Please feel free to contact and discuss with me.
# github:
#   another_url: hunter-lee1.github.io
github:
  is_project_page: false
