title: Shichen Li's Page
logo: assets/me.JPG
theme: jekyll-theme-minimal
description: Please feel free to contact and discuss with me.  Email：scli_21[at]outlook.com
github:
  another_url: https://hunter-lee1.github.io/
# github:
#   is_project_page: false
