title: Shichen Li's Page
logo: assets/me.JPG
theme: jekyll-theme-minimal
blog_description: Please feel free to contact and discuss with me. Email: [scli_21@outlook.com](mailto:scli_21@outlook.com)
github:
  is_project_page: false
